import React from 'react';
import { CheckCircle2, AlertTriangle, ArrowRightCircle, Star } from 'lucide-react';

const VerdictPanel = ({ result }) => {
  const { final_verdict } = result;
  const { overall_score, overall_grade, summary, top_strengths, critical_gaps, recommended_next_steps } = final_verdict;

  return (
    <div className="bg-white rounded-2xl shadow-xl border border-indigo-100 overflow-hidden ring-1 ring-indigo-50">
      <div className="bg-gradient-to-r from-indigo-600 to-indigo-800 p-8 text-white">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div className="space-y-2">
            <div className="flex items-center space-x-2">
              <Star className="w-5 h-5 text-indigo-300 fill-indigo-300" />
              <h3 className="text-xl font-bold tracking-tight">Final Verdict</h3>
            </div>
            <p className="text-indigo-100 text-sm max-w-2xl leading-relaxed">
              {summary}
            </p>
          </div>
          <div className="flex flex-col items-center md:items-end bg-white/10 backdrop-blur-md px-6 py-4 rounded-2xl border border-white/20">
            <span className="text-5xl font-black">{overall_score}</span>
            <span className="text-xs font-bold uppercase tracking-[0.2em] text-indigo-200 mt-1">Overall Score</span>
            <div className="mt-3 px-3 py-1 bg-white text-indigo-700 rounded-full text-[10px] font-black uppercase tracking-widest shadow-lg">
              {overall_grade}
            </div>
          </div>
        </div>
      </div>

      <div className="p-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {/* Top Strengths */}
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-emerald-600 uppercase tracking-widest flex items-center">
              <CheckCircle2 className="w-4 h-4 mr-2" />
              Top Strengths
            </h4>
            <ul className="space-y-3">
              {top_strengths?.map((strength, idx) => (
                <li key={idx} className="flex items-start group">
                  <div className="w-1.5 h-1.5 bg-emerald-500 rounded-full mt-1.5 mr-2.5 flex-shrink-0 group-hover:scale-125 transition-transform" />
                  <span className="text-sm text-gray-700 leading-tight font-medium">{strength}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Critical Gaps */}
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-red-600 uppercase tracking-widest flex items-center">
              <AlertTriangle className="w-4 h-4 mr-2" />
              Critical Gaps
            </h4>
            <ul className="space-y-3">
              {critical_gaps?.map((gap, idx) => (
                <li key={idx} className="flex items-start group">
                  <div className="w-1.5 h-1.5 bg-red-500 rounded-full mt-1.5 mr-2.5 flex-shrink-0 group-hover:scale-125 transition-transform" />
                  <span className="text-sm text-gray-700 leading-tight font-medium">{gap}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Next Steps */}
          <div className="space-y-4">
            <h4 className="text-xs font-bold text-indigo-600 uppercase tracking-widest flex items-center">
              <ArrowRightCircle className="w-4 h-4 mr-2" />
              Recommended Next Steps
            </h4>
            <div className="space-y-3">
              {recommended_next_steps?.map((step, idx) => (
                <div key={idx} className="flex items-start space-x-3 p-3 bg-indigo-50/50 rounded-xl border border-indigo-100/50">
                  <span className="flex items-center justify-center w-5 h-5 bg-indigo-600 text-white text-[10px] font-bold rounded-full flex-shrink-0">
                    {idx + 1}
                  </span>
                  <span className="text-sm text-indigo-900 leading-tight font-semibold">{step}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="bg-gray-50 p-4 text-center border-t border-gray-100">
        <p className="text-[10px] text-gray-400 font-bold uppercase tracking-widest">
          Analysis generated by Resume Analyzer AI Engine • {new Date().toLocaleDateString()}
        </p>
      </div>
    </div>
  );
};

export default VerdictPanel;
